import type { ReportData, KeywordResearchData, BacklinkIntelligence } from './types';

export function generateMockReport(domain: string): ReportData {
  const domainName = domain.replace(/\.(com|org|net|io)$/, '');

  return {
    executive: {
      traffic: 45200,
      trafficChange: 12,
      backlinks: 2340,
      backlinksChange: 156,
      authority: 68,
      authorityChange: -2,
      keywords: 1234,
    },
    backlinks: {
      summary: {
        backlinks: 2340,
        backlinks_num: 2340,
        refdomains: 456,
        refdomains_num: 456,
        subnets: 234,
        ips: 312,
        dofollow_backlinks: 1989,
        nofollow_backlinks: 351,
        text_backlinks: 2100,
        image_backlinks: 200,
        redirect_backlinks: 30,
        canonical_backlinks: 10,
        gov_backlinks: 5,
        edu_backlinks: 12,
        tlds: { com: 1200, org: 300, net: 200, io: 150, co: 100 },
        countries: { US: 1500, UK: 300, DE: 200, FR: 150 },
        top_anchors_by_backlinks: [
          { anchor: domainName, count: 890 },
          { anchor: `${domainName}.com`, count: 456 },
          { anchor: 'click here', count: 234 },
          { anchor: 'visit site', count: 123 },
        ],
        top_anchors_by_refdomains: [
          { anchor: domainName, count: 234 },
          { anchor: `${domainName}.com`, count: 156 },
        ],
      },
      authority: {
        domain_inlink_rank: 68,
        page_inlink_rank: 45,
      },
      momentum: {
        new_backlinks: 156,
        lost_backlinks: 23,
        new_refdomains: 45,
        lost_refdomains: 8,
      },
      indexedPages: [
        { page: '/blog/seo-guide', backlinks: 234, refdomains: 89, dofollow: 200, nofollow: 34 },
        { page: '/tools/free-checker', backlinks: 189, refdomains: 67, dofollow: 150, nofollow: 39 },
        { page: '/pricing', backlinks: 67, refdomains: 34, dofollow: 50, nofollow: 17 },
        { page: '/features', backlinks: 45, refdomains: 23, dofollow: 38, nofollow: 7 },
        { page: '/about', backlinks: 34, refdomains: 18, dofollow: 28, nofollow: 6 },
      ],
      distribution: {
        '0-10': 45,
        '11-20': 28,
        '21-30': 12,
        '31-40': 8,
        '41-50': 4,
        '51-60': 2,
        '61-70': 1,
        '71-80': 0,
        '81-90': 0,
        '91-100': 0,
      },
      intelligence: {
        history: [
          { date: '2025-03-01', backlinks: 1890, refdomains: 320 },
          { date: '2025-04-01', backlinks: 1950, refdomains: 335 },
          { date: '2025-05-01', backlinks: 2010, refdomains: 350 },
          { date: '2025-06-01', backlinks: 2080, refdomains: 368 },
          { date: '2025-07-01', backlinks: 2120, refdomains: 385 },
          { date: '2025-08-01', backlinks: 2180, refdomains: 398 },
          { date: '2025-09-01', backlinks: 2210, refdomains: 412 },
          { date: '2025-10-01', backlinks: 2250, refdomains: 425 },
          { date: '2025-11-01', backlinks: 2280, refdomains: 438 },
          { date: '2025-12-01', backlinks: 2310, refdomains: 448 },
          { date: '2026-01-01', backlinks: 2340, refdomains: 456 },
        ],
        newBacklinks: [
          { url_from: 'https://techcrunch.com/reviews/best-seo-tools', url_to: '/', anchor: 'top SEO software', domain_inlink_rank: 92, date_found: '2026-01-28', dofollow: true, type: 'new' },
          { url_from: 'https://forbes.com/advisor/business/best-seo-tools', url_to: '/', anchor: domainName, domain_inlink_rank: 95, date_found: '2026-01-25', dofollow: true, type: 'new' },
          { url_from: 'https://searchenginejournal.com/seo-tools-guide/123456', url_to: '/features', anchor: 'comprehensive SEO platform', domain_inlink_rank: 88, date_found: '2026-01-22', dofollow: true, type: 'new' },
          { url_from: 'https://blog.hubspot.com/marketing/seo-tools', url_to: '/pricing', anchor: 'click here', domain_inlink_rank: 91, date_found: '2026-01-20', dofollow: false, type: 'new' },
          { url_from: 'https://neilpatel.com/blog/seo-tools', url_to: '/tools', anchor: 'SEO analysis tool', domain_inlink_rank: 85, date_found: '2026-01-18', dofollow: true, type: 'new' },
        ],
        lostBacklinks: [
          { url_from: 'https://oldpartner.com/links/resources', url_to: '/', anchor: domainName, domain_inlink_rank: 34, date_lost: '2026-01-30', dofollow: true, type: 'lost' },
          { url_from: 'https://defunct-blog.net/seo-roundup', url_to: '/blog', anchor: 'visit site', domain_inlink_rank: 22, date_lost: '2026-01-27', dofollow: true, type: 'lost' },
        ],
        ipConcentration: [
          { ip: '192.168.x.x', backlinks: 234, percentage: 10.0, riskLevel: 'medium' },
          { ip: '10.0.x.x', backlinks: 189, percentage: 8.1, riskLevel: 'medium' },
          { ip: '172.16.x.x', backlinks: 156, percentage: 6.7, riskLevel: 'low' },
          { ip: '54.23.x.x', backlinks: 120, percentage: 5.1, riskLevel: 'low' },
          { ip: '35.192.x.x', backlinks: 98, percentage: 4.2, riskLevel: 'low' },
        ],
        netChange: {
          backlinks: 133,
          refdomains: 37,
          period: '30 days',
        },
      },
    },
    keywords: {
      total: 1234,
      topKeywords: [
        { keyword: 'seo software', position: 3, prev_position: 5, volume: 12100, cpc: 15.5, competition: 0.85, difficulty: 65, traffic: 2890, traffic_percent: 6.4, url: '/features', serp_features: ['featured_snippet'] },
        { keyword: 'rank tracker', position: 5, prev_position: 7, volume: 8100, cpc: 12.3, competition: 0.78, difficulty: 72, traffic: 1234, traffic_percent: 2.7, url: '/tools/rank-tracker', serp_features: [] },
        { keyword: 'backlink checker', position: 7, prev_position: 6, volume: 5400, cpc: 8.9, competition: 0.72, difficulty: 58, traffic: 567, traffic_percent: 1.3, url: '/tools/backlink-checker', serp_features: ['video'] },
        { keyword: 'site audit tool', position: 12, prev_position: 15, volume: 3600, cpc: 7.2, competition: 0.65, difficulty: 45, traffic: 123, traffic_percent: 0.3, url: '/tools/site-audit', serp_features: [] },
        { keyword: 'keyword research', position: 8, prev_position: 10, volume: 14800, cpc: 18.5, competition: 0.92, difficulty: 78, traffic: 890, traffic_percent: 2.0, url: '/tools/keyword-research', serp_features: ['featured_snippet', 'people_also_ask'] },
      ],
      nearPageOne: [
        { keyword: 'seo audit tool', position: 11, prev_position: 14, volume: 5400, cpc: 9.2, competition: 0.7, difficulty: 52, traffic: 120, traffic_percent: 0.3, url: '/tools/site-audit', serp_features: [] },
        { keyword: 'rank tracker free', position: 14, prev_position: 18, volume: 3200, cpc: 6.8, competition: 0.58, difficulty: 48, traffic: 85, traffic_percent: 0.2, url: '/tools/rank-tracker', serp_features: [] },
        { keyword: 'backlink analysis', position: 12, prev_position: 11, volume: 2900, cpc: 7.5, competition: 0.65, difficulty: 55, traffic: 90, traffic_percent: 0.2, url: '/tools/backlink-checker', serp_features: [] },
        { keyword: 'keyword difficulty', position: 18, prev_position: 22, volume: 2100, cpc: 5.4, competition: 0.52, difficulty: 42, traffic: 45, traffic_percent: 0.1, url: '/blog/keyword-difficulty', serp_features: [] },
      ],
      positionDistribution: {
        top3: 23,
        top10: 41,
        top20: 53,
        top50: 84,
        top100: 129,
      },
      history: [
        { date: '2026-01-01', year: 2026, month: 1, traffic: 45200, keywords: 1180, traffic_cost: 125000, top1_5: 18, top6_10: 23, top11_20: 35, top21_50: 48, top51_100: 56 },
        { date: '2025-12-01', year: 2025, month: 12, traffic: 43800, keywords: 1150, traffic_cost: 121000, top1_5: 16, top6_10: 22, top11_20: 33, top21_50: 45, top51_100: 54 },
        { date: '2025-11-01', year: 2025, month: 11, traffic: 42100, keywords: 1120, traffic_cost: 118000, top1_5: 15, top6_10: 20, top11_20: 32, top21_50: 43, top51_100: 52 },
        { date: '2025-10-01', year: 2025, month: 10, traffic: 40500, keywords: 1080, traffic_cost: 114000, top1_5: 14, top6_10: 19, top11_20: 30, top21_50: 41, top51_100: 50 },
        { date: '2025-09-01', year: 2025, month: 9, traffic: 38900, keywords: 1050, traffic_cost: 110000, top1_5: 13, top6_10: 18, top11_20: 28, top21_50: 39, top51_100: 48 },
        { date: '2025-08-01', year: 2025, month: 8, traffic: 37200, keywords: 1020, traffic_cost: 106000, top1_5: 12, top6_10: 17, top11_20: 27, top21_50: 37, top51_100: 46 },
      ],
      research: {
        seedKeyword: 'seo software',
        similarKeywords: [
          { keyword: 'seo tools', volume: 12000, difficulty: 68, cpc: 14.5, competition: 0.82 },
          { keyword: 'seo platform', volume: 8200, difficulty: 62, cpc: 12.8, competition: 0.75 },
          { keyword: 'seo analyzer', volume: 5100, difficulty: 55, cpc: 9.2, competition: 0.68 },
          { keyword: 'seo checker', volume: 4200, difficulty: 52, cpc: 8.5, competition: 0.65 },
          { keyword: 'seo suite', volume: 2800, difficulty: 48, cpc: 7.8, competition: 0.58 },
        ],
        relatedKeywords: [
          { keyword: 'search engine optimization', volume: 18000, difficulty: 75, cpc: 18.2, competition: 0.88 },
          { keyword: 'website ranking checker', volume: 6500, difficulty: 45, cpc: 8.9, competition: 0.62 },
          { keyword: 'organic traffic tools', volume: 3200, difficulty: 42, cpc: 7.2, competition: 0.55 },
          { keyword: 'keyword tracking software', volume: 2400, difficulty: 38, cpc: 6.8, competition: 0.52 },
          { keyword: 'backlink monitoring', volume: 1800, difficulty: 35, cpc: 5.5, competition: 0.48 },
        ],
        longTailKeywords: [
          { keyword: 'best seo software for small business', volume: 2400, difficulty: 35, cpc: 12.5, competition: 0.58 },
          { keyword: 'free seo software tools', volume: 1800, difficulty: 28, cpc: 8.2, competition: 0.45 },
          { keyword: 'seo software comparison 2026', volume: 900, difficulty: 22, cpc: 15.8, competition: 0.42 },
          { keyword: 'enterprise seo software', volume: 650, difficulty: 45, cpc: 22.5, competition: 0.72 },
          { keyword: 'affordable seo software for agencies', volume: 480, difficulty: 32, cpc: 14.2, competition: 0.55 },
        ],
        sweetSpotKeywords: [
          { keyword: 'website ranking checker', volume: 6500, difficulty: 45, cpc: 8.9, competition: 0.62 },
          { keyword: 'organic traffic tools', volume: 3200, difficulty: 42, cpc: 7.2, competition: 0.55 },
          { keyword: 'best seo software for small business', volume: 2400, difficulty: 35, cpc: 12.5, competition: 0.58 },
          { keyword: 'keyword tracking software', volume: 2400, difficulty: 38, cpc: 6.8, competition: 0.52 },
          { keyword: 'free seo software tools', volume: 1800, difficulty: 28, cpc: 8.2, competition: 0.45 },
          { keyword: 'backlink monitoring', volume: 1800, difficulty: 35, cpc: 5.5, competition: 0.48 },
        ],
      },
    },
    domainAnalysis: {
      authority: 65,
      trafficByCountry: [
        { source: 'us', country: 'United States', traffic: 28000, keywords: 850, percentage: 62 },
        { source: 'uk', country: 'United Kingdom', traffic: 8500, keywords: 320, percentage: 19 },
        { source: 'de', country: 'Germany', traffic: 4200, keywords: 180, percentage: 9 },
        { source: 'fr', country: 'France', traffic: 2500, keywords: 120, percentage: 6 },
        { source: 'es', country: 'Spain', traffic: 1800, keywords: 90, percentage: 4 },
      ],
      subdomains: [
        { subdomain: 'www.example.com', traffic: 35000, keywords: 1200 },
        { subdomain: 'blog.example.com', traffic: 8500, keywords: 450 },
        { subdomain: 'docs.example.com', traffic: 2200, keywords: 180 },
        { subdomain: 'api.example.com', traffic: 500, keywords: 25 },
      ],
      trafficTrend: [
        { date: '2026-01-01', year: 2026, month: 1, traffic: 45200, keywords: 1180, traffic_cost: 125000, top1_5: 18, top6_10: 24, top11_20: 35, top21_50: 48, top51_100: 58 },
        { date: '2025-12-01', year: 2025, month: 12, traffic: 43800, keywords: 1150, traffic_cost: 121000, top1_5: 16, top6_10: 22, top11_20: 33, top21_50: 45, top51_100: 54 },
        { date: '2025-11-01', year: 2025, month: 11, traffic: 42100, keywords: 1120, traffic_cost: 118000, top1_5: 15, top6_10: 20, top11_20: 32, top21_50: 43, top51_100: 52 },
      ],
      topPagesByTraffic: [
        { url: '/blog/seo-guide', traffic: 8500, keywords: 45 },
        { url: '/tools/keyword-research', traffic: 6200, keywords: 32 },
        { url: '/pricing', traffic: 4800, keywords: 18 },
        { url: '/blog/backlink-strategies', traffic: 3200, keywords: 28 },
        { url: '/features', traffic: 2900, keywords: 15 },
      ],
      topPagesByBacklinks: [
        { page: '/', backlinks: 12500, refdomains: 890, dofollow: 11000, nofollow: 1500 },
        { page: '/blog/seo-guide', backlinks: 3200, refdomains: 420, dofollow: 2800, nofollow: 400 },
        { page: '/tools', backlinks: 1800, refdomains: 280, dofollow: 1600, nofollow: 200 },
      ],
      anchorTextDistribution: [
        { anchor: 'brand name', count: 4500 },
        { anchor: 'seo tool', count: 1200 },
        { anchor: 'keyword research', count: 890 },
        { anchor: 'click here', count: 650 },
        { anchor: 'website', count: 420 },
      ],
      refDomainsDistribution: {
        '0-10': 120,
        '11-20': 450,
        '21-30': 890,
        '31-40': 650,
        '41-50': 420,
        '51-60': 280,
        '61-70': 180,
        '71-80': 95,
        '81-90': 45,
        '91-100': 12,
      },
    },
    competitive: {
      competitors: [
        { domain: 'semrush.com', common_keywords: 1234, keywords: 2500000, traffic: 2100000, traffic_cost: 45000000, overlap: 67 },
        { domain: 'ahrefs.com', common_keywords: 987, keywords: 1800000, traffic: 1800000, traffic_cost: 38000000, overlap: 58 },
        { domain: 'moz.com', common_keywords: 567, keywords: 890000, traffic: 890000, traffic_cost: 12000000, overlap: 45 },
      ],
      competitorComparison: [
        { domain: 'semrush.com', traffic: 2100000, keywords: 2500000, authority: 92, backlinks: 45000000, common_keywords: 1234, overlap: 67 },
        { domain: 'ahrefs.com', traffic: 1800000, keywords: 1800000, authority: 91, backlinks: 38000000, common_keywords: 987, overlap: 58 },
        { domain: 'moz.com', traffic: 890000, keywords: 890000, authority: 85, backlinks: 12000000, common_keywords: 567, overlap: 45 },
      ],
      keywordGaps: [
        { keyword: 'seo audit checklist', volume: 4400, difficulty: 52, competitor_position: 3, our_position: null },
        { keyword: 'keyword clustering', volume: 2900, difficulty: 48, competitor_position: 5, our_position: null },
        { keyword: 'serp analysis tool', volume: 1600, difficulty: 38, competitor_position: 2, our_position: null },
        { keyword: 'backlink gap', volume: 1200, difficulty: 41, competitor_position: 4, our_position: null },
        { keyword: 'content gap analysis', volume: 880, difficulty: 35, competitor_position: 1, our_position: null },
      ],
      keywordOverlap: [
        { keyword: 'seo tools', volume: 22000, ourPosition: 5, competitorPosition: 2 },
        { keyword: 'backlink checker', volume: 18000, ourPosition: 8, competitorPosition: 3 },
        { keyword: 'rank tracker', volume: 12000, ourPosition: 4, competitorPosition: 6 },
      ],
      backlinkGaps: [
        { domain: 'searchengineland.com', domain_inlink_rank: 85, backlinks_to_competitor: 234 },
        { domain: 'marketingland.com', domain_inlink_rank: 78, backlinks_to_competitor: 156 },
        { domain: 'techcrunch.com', domain_inlink_rank: 92, backlinks_to_competitor: 89 },
      ],
    },
    aiSearch: {
      overview: {
        target: domain,
        engines: [
          { engine: 'Google AI Overview', brand_presence: 156, link_presence: 234, traffic: 1200 },
          { engine: 'ChatGPT', brand_presence: 23, link_presence: 45, traffic: 450 },
          { engine: 'Perplexity', brand_presence: 45, link_presence: 89, traffic: 380 },
          { engine: 'Gemini', brand_presence: 12, link_presence: 18, traffic: 120 },
        ],
      },
      leaderboard: [
        { rank: 1, domain: 'semrush.com', brand: 'Semrush', share_of_voice: 34, brand_mentions: 890, link_citations: 1200 },
        { rank: 2, domain: 'ahrefs.com', brand: 'Ahrefs', share_of_voice: 28, brand_mentions: 720, link_citations: 980 },
        { rank: 3, domain: domain, brand: domainName, share_of_voice: 16, brand_mentions: 236, link_citations: 386 },
        { rank: 4, domain: 'moz.com', brand: 'Moz', share_of_voice: 12, brand_mentions: 180, link_citations: 245 },
        { rank: 5, domain: 'serpstat.com', brand: 'Serpstat', share_of_voice: 10, brand_mentions: 120, link_citations: 180 },
      ],
      prompts: [
        {
          prompt: 'best seo tools 2026',
          engine: 'chatgpt',
          type: 'brand_link',
          position: 2,
          volume: 12400,
          answer_snippet: 'The best SEO tools in 2026 include a variety of comprehensive platforms that help with keyword research, backlink analysis...',
          answer_full: 'The best SEO tools in 2026 include a variety of comprehensive platforms that help with keyword research, backlink analysis, and site audits. Leading options include:\n\n1. **Semrush** - An all-in-one SEO suite offering keyword research, competitor analysis, rank tracking, and site auditing capabilities.\n\n2. **Ahrefs** - Known for its powerful backlink analysis and content explorer features, making it ideal for link building strategies.\n\n3. **Moz Pro** - Offers a comprehensive SEO toolkit with domain authority metrics and page optimization suggestions.\n\n4. **SE Ranking** - Provides excellent AI search visibility tracking alongside traditional SEO features.',
          sources: [
            'https://www.semrush.com/blog/best-seo-tools/',
            'https://ahrefs.com/blog/seo-tools/',
            'https://searchengineland.com/best-seo-tools-guide-2026',
            'https://moz.com/learn/seo/seo-tools',
          ],
        },
        {
          prompt: 'how to track keyword rankings',
          engine: 'perplexity',
          type: 'link',
          position: 3,
          volume: 8900,
          answer_snippet: 'To track keyword rankings effectively, you need to use a rank tracking tool that monitors your positions in search...',
          answer_full: 'To track keyword rankings effectively, you need to use a rank tracking tool that monitors your positions in search engine results pages (SERPs) over time. Here\'s how to do it:\n\n**Step 1: Choose a Rank Tracker**\nSelect a reliable rank tracking tool like SE Ranking, Semrush, or Ahrefs. These tools allow you to monitor your keyword positions daily or weekly.\n\n**Step 2: Add Your Keywords**\nImport your target keywords into the tool. Focus on keywords that drive business value.\n\n**Step 3: Set Up Tracking Locations**\nConfigure geographic targeting to track rankings in specific countries, cities, or even zip codes.\n\n**Step 4: Monitor Competitors**\nAdd competitor domains to compare your rankings against industry peers.\n\n**Step 5: Analyze Trends**\nReview ranking trends over time to identify opportunities and issues.',
          sources: [
            'https://seranking.com/blog/rank-tracking-guide/',
            'https://www.searchenginejournal.com/rank-tracking-tools/',
            'https://backlinko.com/track-google-rankings',
          ],
        },
        {
          prompt: 'backlink checker free',
          engine: 'ai-overview',
          type: 'brand',
          position: 5,
          volume: 14500,
          answer_snippet: 'There are several free backlink checkers available that can help you analyze your website\'s link profile...',
          answer_full: 'There are several free backlink checkers available that can help you analyze your website\'s link profile:\n\n• **Ahrefs Free Backlink Checker** - Shows top 100 backlinks with key metrics\n• **Ubersuggest** - Provides backlink overview with limited free searches\n• **Google Search Console** - Shows linking domains for verified sites\n• **SE Ranking** - Offers a free trial with comprehensive backlink analysis\n• **Moz Link Explorer** - Free tier shows basic backlink data\n\nNote that free tools typically have limitations on the number of queries or depth of data. For comprehensive analysis, paid tools offer more complete data.',
          sources: [
            'https://ahrefs.com/backlink-checker',
            'https://neilpatel.com/ubersuggest/',
            'https://search.google.com/search-console/about',
            'https://seranking.com/backlink-checker.html',
            'https://moz.com/link-explorer',
          ],
        },
        {
          prompt: 'competitor analysis seo',
          engine: 'gemini',
          type: 'brand_link',
          position: 4,
          volume: 6700,
          answer_snippet: 'SEO competitor analysis involves researching your competitors\' strategies to identify opportunities for your own site...',
          answer_full: 'SEO competitor analysis involves researching your competitors\' strategies to identify opportunities for your own site. Here\'s a comprehensive approach:\n\n**1. Identify Your Competitors**\nUse tools like Semrush or SE Ranking to find domains ranking for your target keywords.\n\n**2. Analyze Their Keywords**\nDiscover which keywords drive traffic to competitor sites and identify gaps in your own strategy.\n\n**3. Study Their Backlinks**\nExamine competitor backlink profiles to find link-building opportunities.\n\n**4. Review Their Content**\nAnalyze top-performing content to understand what resonates with your audience.\n\n**5. Monitor SERP Features**\nTrack which competitors appear in featured snippets, AI overviews, and other SERP features.\n\n**6. Track Changes Over Time**\nSet up ongoing monitoring to stay ahead of competitor movements.',
          sources: [
            'https://www.semrush.com/blog/competitor-analysis/',
            'https://seranking.com/competitor-analysis.html',
          ],
        },
      ],
      market: 'us',
      marketName: 'United States',
    },
    contentOpportunities: {
      questionKeywords: [
        { keyword: 'what is the best seo tool?', volume: 2400, difficulty: 45, cpc: 8.5 },
        { keyword: 'how to check website ranking?', volume: 1900, difficulty: 38, cpc: 6.2 },
        { keyword: 'how to find competitor keywords?', volume: 1200, difficulty: 42, cpc: 7.8 },
        { keyword: 'what is domain authority?', volume: 880, difficulty: 35, cpc: 5.4 },
      ],
      gaps: [
        { keyword: 'seo audit checklist', volume: 4400, difficulty: 52, competitor_position: 3, our_position: null },
        { keyword: 'keyword clustering', volume: 2900, difficulty: 48, competitor_position: 5, our_position: null },
        { keyword: 'serp analysis tool', volume: 1600, difficulty: 38, competitor_position: 2, our_position: null },
      ],
    },
    quickWins: {
      nearPageOneKeywords: [
        { keyword: 'seo audit tool', position: 11, prev_position: 14, volume: 5400, cpc: 9.2, competition: 0.7, difficulty: 52, traffic: 120, traffic_percent: 0.3, url: '/tools/site-audit', serp_features: [] },
        { keyword: 'rank tracker free', position: 14, prev_position: 18, volume: 3200, cpc: 6.8, competition: 0.58, difficulty: 48, traffic: 85, traffic_percent: 0.2, url: '/tools/rank-tracker', serp_features: [] },
        { keyword: 'backlink analysis', position: 12, prev_position: 11, volume: 2900, cpc: 7.5, competition: 0.65, difficulty: 55, traffic: 90, traffic_percent: 0.2, url: '/tools/backlink-checker', serp_features: [] },
      ],
      lowHangingFruit: [
        { type: 'technical', description: 'Fix 12 critical technical SEO issues', impact: 'high', effort: 'low' },
        { type: 'keywords', description: 'Optimize 4 keywords in positions 11-20 (potential +1,930 visits/mo)', impact: 'high', effort: 'medium' },
        { type: 'content', description: 'Create content for 5 keyword gaps (10,980 monthly searches)', impact: 'high', effort: 'medium' },
      ],
    },
  };
}
